In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 6]]
x = torch.tensor(data)
x, type(x), x.dim, x.shape, x.ndim, x.type

(tensor([[1, 2],
         [3, 6]]),
 torch.Tensor,
 <function Tensor.dim>,
 torch.Size([2, 2]),
 2,
 <function Tensor.type>)

In [4]:
x.shape

torch.Size([2, 2])

In [5]:
npa = np.array(data)
npa

array([[1, 2],
       [3, 6]])

In [8]:
y = torch.from_numpy(npa)
y, type(y), y.type, y.type()

(tensor([[1, 2],
         [3, 6]], dtype=torch.int32),
 torch.Tensor,
 <function Tensor.type>,
 'torch.IntTensor')

In [9]:
o = torch.ones(size=(3, 2))
o

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
torch.zeros_like(o)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
torch.randint_like(o, high=15, low=5)

tensor([[ 8.,  7.],
        [13., 12.],
        [13., 14.]])

In [13]:
torch.randint(size=(2, 2), high=6, low=-1)

tensor([[3, 1],
        [4, 4]])

In [14]:
torch.rand_like(input=o, dtype=torch.float)

tensor([[0.5063, 0.9077],
        [0.7241, 0.6844],
        [0.5400, 0.7559]])

In [15]:
r = torch.rand(2, 3)
r, r.dtype, r.shape, r.type(), r.device

(tensor([[0.3702, 0.9576, 0.7677],
         [0.2281, 0.5451, 0.6680]]),
 torch.float32,
 torch.Size([2, 3]),
 'torch.FloatTensor',
 device(type='cpu'))

## Operations on tensors

- By default tensors are created on the CPU and we need to explicitely move tensors to GPU using .to method.

In [16]:
if torch.cuda.is_available():
    r = r.to(device="cuda")

In [17]:
r

tensor([[0.3702, 0.9576, 0.7677],
        [0.2281, 0.5451, 0.6680]])

In [18]:
r[:, 1] = 0
r

tensor([[0.3702, 0.0000, 0.7677],
        [0.2281, 0.0000, 0.6680]])

In [21]:
torch.concat([r, r], 1), torch.concat([r, r, r])

(tensor([[0.3702, 0.0000, 0.7677, 0.3702, 0.0000, 0.7677],
         [0.2281, 0.0000, 0.6680, 0.2281, 0.0000, 0.6680]]),
 tensor([[0.3702, 0.0000, 0.7677],
         [0.2281, 0.0000, 0.6680],
         [0.3702, 0.0000, 0.7677],
         [0.2281, 0.0000, 0.6680],
         [0.3702, 0.0000, 0.7677],
         [0.2281, 0.0000, 0.6680]]))

In [22]:
torch.cat([r, r])

tensor([[0.3702, 0.0000, 0.7677],
        [0.2281, 0.0000, 0.6680],
        [0.3702, 0.0000, 0.7677],
        [0.2281, 0.0000, 0.6680]])

In [23]:
torch.matmul(r, r.T), r @ r.T

(tensor([[0.7264, 0.5973],
         [0.5973, 0.4982]]),
 tensor([[0.7264, 0.5973],
         [0.5973, 0.4982]]))

In [24]:
torch.mul(r, r), torch.multiply(r, r), r*r

(tensor([[0.1371, 0.0000, 0.5894],
         [0.0520, 0.0000, 0.4462]]),
 tensor([[0.1371, 0.0000, 0.5894],
         [0.0520, 0.0000, 0.4462]]),
 tensor([[0.1371, 0.0000, 0.5894],
         [0.0520, 0.0000, 0.4462]]))

In [28]:
r, r.sum(dim=1), r.sum(dim=0)

(tensor([[0.3702, 0.0000, 0.7677],
         [0.2281, 0.0000, 0.6680]]),
 tensor([1.1379, 0.8961]),
 tensor([0.5984, 0.0000, 1.4357]))

In [31]:
r.sum(), r.sum().item()

(tensor(2.0340), 2.034041404724121)

### Implace operation "_"

In [32]:
r.add_(3)

tensor([[3.3702, 3.0000, 3.7677],
        [3.2281, 3.0000, 3.6680]])

In [33]:
r

tensor([[3.3702, 3.0000, 3.7677],
        [3.2281, 3.0000, 3.6680]])

In [34]:
r.add(3)

tensor([[6.3702, 6.0000, 6.7677],
        [6.2281, 6.0000, 6.6680]])

In [35]:
r

tensor([[3.3702, 3.0000, 3.7677],
        [3.2281, 3.0000, 3.6680]])

## Bridge with numpy

- tensor on CPU and numpy arrays can share their underlying memory locations, and changing one will change the other.

In [36]:
t = torch.randint(size=(3, 4), low=10, high=20)
t

tensor([[19, 13, 14, 10],
        [13, 11, 12, 18],
        [11, 18, 10, 14]])

In [37]:
type(t), t.dtype, t.type, t.type()

(torch.Tensor, torch.int64, <function Tensor.type>, 'torch.LongTensor')

In [40]:
n = t.numpy()
type(n), n.dtype

(numpy.ndarray, dtype('int64'))

In [41]:
t.add_(1)

tensor([[20, 14, 15, 11],
        [14, 12, 13, 19],
        [12, 19, 11, 15]])

In [42]:
t, n

(tensor([[20, 14, 15, 11],
         [14, 12, 13, 19],
         [12, 19, 11, 15]]),
 array([[20, 14, 15, 11],
        [14, 12, 13, 19],
        [12, 19, 11, 15]], dtype=int64))

So, change in one changed the other

In [43]:
n2 = np.array([[3, 7], [11, 7]])
t2 = torch.from_numpy(n2)

n2, t2

(array([[ 3,  7],
        [11,  7]]),
 tensor([[ 3,  7],
         [11,  7]], dtype=torch.int32))

In [44]:
np.add(n2, 2)

array([[ 5,  9],
       [13,  9]])

In [45]:
n2, t2

(array([[ 3,  7],
        [11,  7]]),
 tensor([[ 3,  7],
         [11,  7]], dtype=torch.int32))

In [46]:
t2.add_(1)

tensor([[ 4,  8],
        [12,  8]], dtype=torch.int32)

In [47]:
n2, t2

(array([[ 4,  8],
        [12,  8]]),
 tensor([[ 4,  8],
         [12,  8]], dtype=torch.int32))

In [48]:
n2 = np.add(n2, 1)
n2, t2

(array([[ 5,  9],
        [13,  9]]),
 tensor([[ 4,  8],
         [12,  8]], dtype=torch.int32))