In [1]:
import tensorflow as tf
import torch
from IPython.display import display, Math

import warnings
warnings.filterwarnings('ignore')

## Using PyTorch

In [2]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)
c = torch.tensor([5.0], requires_grad=True)
d = torch.tensor([10.0], requires_grad=True)

t = torch.log(d)

u = a*b
v = t*c

# retain_grad() allows us to calculate grad of a varible despite it not being a leaf node
t.retain_grad()
u.retain_grad()
e = u+v

a.requires_grad, t.requires_grad, u.requires_grad

(True, True, True)

In [3]:
u, v, e, t

(tensor([6.], grad_fn=<MulBackward0>),
 tensor([11.5129], grad_fn=<MulBackward0>),
 tensor([17.5129], grad_fn=<AddBackward0>),
 tensor([2.3026], grad_fn=<LogBackward0>))

In [4]:
print(f'a is leaf: {a.is_leaf}') # variables which are directly created by the user are leaf node
print(f'a.grad_fn: {a.grad_fn}')
print(f'a.grad: {a.grad}\n')

print(f'b is leaf: {b.is_leaf}')
print(f'b.grad_fn: {b.grad_fn}')
print(f'b.grad: {b.grad}\n')

print(f'c is leaf: {c.is_leaf}')
print(f'c.grad_fn: {c.grad_fn}')
print(f'c.grad: {c.grad}\n')

print(f'd is leaf: {d.is_leaf}')
print(f'd.grad_fn: {d.grad_fn}')
print(f'd.grad: {d.grad}\n')

print(f't is leaf: {t.is_leaf}') # varaibles not created by the user and which depends on other varibles are not leaf node
print(f't.grad_fn: {t.grad_fn}')
print(f't.grad: {t.grad}\n')

print(f'e is leaf: {e.is_leaf}')
print(f'e.grad_fn: {e.grad_fn}')
print(f'e.grad: {e.grad}\n')

print(f'u is leaf: {u.is_leaf}')
print(f'u.grad_fn: {u.grad_fn}')
print(f'u.grad: {u.grad}\n')

print(f'v is leaf: {v.is_leaf}')
print(f'v.grad_fn: {v.grad_fn}')
print(f'v.grad: {v.grad}\n')

a is leaf: True
a.grad_fn: None
a.grad: None

b is leaf: True
b.grad_fn: None
b.grad: None

c is leaf: True
c.grad_fn: None
c.grad: None

d is leaf: True
d.grad_fn: None
d.grad: None

t is leaf: False
t.grad_fn: <LogBackward0 object at 0x0000023BBFB9F970>
t.grad: None

e is leaf: False
e.grad_fn: <AddBackward0 object at 0x0000023BBFB9F970>
e.grad: None

u is leaf: False
u.grad_fn: <MulBackward0 object at 0x0000023BBFB9F970>
u.grad: None

v is leaf: False
v.grad_fn: <MulBackward0 object at 0x0000023BBFB9F970>
v.grad: None



In [5]:
e.backward(retain_graph=True)

In [6]:
t.grad, u.grad, v.grad

(tensor([5.]), tensor([1.]), None)

In [7]:
a.grad, b.grad, c.grad, d.grad

(tensor([3.]), tensor([2.]), tensor([2.3026]), tensor([0.5000]))

In [8]:
print(f'a is leaf: {a.is_leaf}')
print(f'a.grad_fn: {a.grad_fn}')
print(f'a.grad: {a.grad}\n')

print(f'b is leaf: {b.is_leaf}')
print(f'b.grad_fn: {b.grad_fn}')
print(f'b.grad: {b.grad}\n')

print(f'c is leaf: {c.is_leaf}')
print(f'c.grad_fn: {c.grad_fn}')
print(f'c.grad: {c.grad}\n')

print(f'd is leaf: {d.is_leaf}')
print(f'd.grad_fn: {d.grad_fn}')
print(f'd.grad: {d.grad}\n')

print(f't is leaf: {t.is_leaf}')
print(f't.grad_fn: {t.grad_fn}')
print(f't.grad: {t.grad}\n')

print(f'e is leaf: {e.is_leaf}')
print(f'e.grad_fn: {e.grad_fn}')
print(f'e.grad: {e.grad}\n')

print(f'u is leaf: {u.is_leaf}')
print(f'u.grad_fn: {u.grad_fn}')
print(f'u.grad: {u.grad}\n')

print(f'v is leaf: {v.is_leaf}')
print(f'v.grad_fn: {v.grad_fn}')
print(f'v.grad: {v.grad}\n')

a is leaf: True
a.grad_fn: None
a.grad: tensor([3.])

b is leaf: True
b.grad_fn: None
b.grad: tensor([2.])

c is leaf: True
c.grad_fn: None
c.grad: tensor([2.3026])

d is leaf: True
d.grad_fn: None
d.grad: tensor([0.5000])

t is leaf: False
t.grad_fn: <LogBackward0 object at 0x0000023BBFB9F970>
t.grad: tensor([5.])

e is leaf: False
e.grad_fn: <AddBackward0 object at 0x0000023BBFB9F970>
e.grad: None

u is leaf: False
u.grad_fn: <MulBackward0 object at 0x0000023BBFB9F970>
u.grad: tensor([1.])

v is leaf: False
v.grad_fn: <MulBackward0 object at 0x0000023BBFB9F970>
v.grad: None



In [9]:
# e.backward() => This won't run as its value is deleted by the system to save memory. If we want to run it, use retain_graph=True in previous e.backward()

In [10]:
e.backward() # this ran as retain_graph was set True this time. (Though it will run only once unless retain_graph is set here.)

## Using Tensorflow

In [14]:
a = tf.constant(2.0)
a.dtype, a.shape, a.ndim, tf.size(a), tf.shape(a)

(tf.float32,
 TensorShape([]),
 0,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>)

In [15]:
a = tf.constant(2.0)
b = tf.constant(3.0)
c = tf.constant(5.0)
d = tf.constant(10.0)

t = tf.math.log(d)

u = tf.multiply(a, b)
v = tf.multiply(t, c)

e = tf.add(u, v)

a, e, u, v, t

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=17.512926>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=11.512926>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>)

In [20]:
with tf.GradientTape() as tape:
    tape.watch([a, b, c, d])
    t = tf.math.log(d)
    u = tf.multiply(a, b)
    v = tf.multiply(t, c)
    e = tf.add(u, v)
    
gradients = tape.gradient(e, [a, b, c, d])

In [22]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5>]

In [27]:
print(f"Gradients= a:{gradients[0]}, b: {gradients[1]}, c: {gradients[2]:.2f}, d: {gradients[3]}")

Gradients= a:3.0, b: 2.0, c: 2.30, d: 0.5
